from __future__ import annotations

SEED_SYLLABUS_MAPS = [
    {
        "id": "IGCSE_PHYSICS_P4_MOTION_1_1_1",
        "objective_id": "CAIE_0625_P4_1.1.1_A",
        "board": "IGCSE",
        "subject": "Physics",
        "paper": "Paper 4",
        "topic": "Motion",
        "sub_topic": "Kinematics",
        "code": "1.1.1",
        "title": "Speed, velocity, and acceleration",
        "description": "Use speed, velocity, and acceleration correctly in written and calculation responses.",
        "paper_weight": 0.22,
        "command_words": ["Define", "Describe", "Explain", "Calculate"],
    },
    {
        "id": "IGCSE_PHYSICS_P4_FORCES_1_6_1",
        "objective_id": "CAIE_0625_P4_1.6.1_A",
        "board": "IGCSE",
        "subject": "Physics",
        "paper": "Paper 4",
        "topic": "Forces",
        "sub_topic": "Momentum",
        "code": "1.6.1",
        "title": "Momentum and force relationships",
        "description": "Apply momentum and force relationships in structured responses and calculations.",
        "paper_weight": 0.30,
        "command_words": ["Explain", "Calculate", "Compare"],
    },
    {
        "id": "IGCSE_PHYSICS_P6_ELECTRICITY_4_2_1",
        "objective_id": "CAIE_0625_P6_4.2.1_A",
        "board": "IGCSE",
        "subject": "Physics",
        "paper": "Paper 6",
        "topic": "Electricity",
        "sub_topic": "Circuits",
        "code": "4.2.1",
        "title": "Circuit interpretation",
        "description": "Interpret circuit evidence and explain electrical relationships using experiment data.",
        "paper_weight": 0.18,
        "command_words": ["Describe", "Explain", "Evaluate"],
    },
    {
        "id": "IGCSE_MATHS_P2_ALGEBRA_2_1_1",
        "objective_id": "CAIE_0580_P2_2.1.1_A",
        "board": "IGCSE",
        "subject": "Mathematics",
        "paper": "Paper 2",
        "topic": "Algebra",
        "sub_topic": "Manipulation",
        "code": "2.1.1",
        "title": "Algebraic manipulation",
        "description": "Manipulate algebraic expressions accurately under exam conditions.",
        "paper_weight": 0.24,
        "command_words": ["Calculate", "Simplify", "Solve"],
    },
    {
        "id": "IGCSE_MATHS_P4_TRIGONOMETRY_4_3_1",
        "objective_id": "CAIE_0580_P4_4.3.1_A",
        "board": "IGCSE",
        "subject": "Mathematics",
        "paper": "Paper 4",
        "topic": "Trigonometry",
        "sub_topic": "Non-right-angle Trigonometry",
        "code": "4.3.1",
        "title": "Right-angle and non-right-angle trigonometry",
        "description": "Solve right-angle and non-right-angle trigonometry problems accurately.",
        "paper_weight": 0.16,
        "command_words": ["Calculate", "Solve"],
    },
    {
        "id": "ALEVEL_PHYSICS_P2_MOMENTUM_P2_4",
        "objective_id": "CAIE_9702_P2_P2.4_A",
        "board": "A Level",
        "subject": "Physics",
        "paper": "Paper 2",
        "topic": "Momentum",
        "sub_topic": "Impulse",
        "code": "P2.4",
        "title": "Momentum and impulse",
        "description": "Model momentum and impulse with correct sign conventions and units.",
        "paper_weight": 0.28,
        "command_words": ["Explain", "Calculate", "Evaluate"],
    },
    {
        "id": "ALEVEL_PHYSICS_P4_CIRCULAR_MOTION_P4_2",
        "objective_id": "CAIE_9702_P4_P4.2_A",
        "board": "A Level",
        "subject": "Physics",
        "paper": "Paper 4",
        "topic": "Circular Motion",
        "sub_topic": "Centripetal Force",
        "code": "P4.2",
        "title": "Circular motion",
        "description": "Explain circular motion using resultant force and angular relationships.",
        "paper_weight": 0.26,
        "command_words": ["Explain", "Compare", "Evaluate"],
    },
    {
        "id": "ALEVEL_MATHS_P1_DIFFERENTIATION_M1_5",
        "objective_id": "CAIE_9709_P1_M1.5_A",
        "board": "A Level",
        "subject": "Mathematics",
        "paper": "Pure 1",
        "topic": "Differentiation",
        "sub_topic": "Composite Functions",
        "code": "M1.5",
        "title": "Differentiation techniques",
        "description": "Differentiate composite and standard polynomial functions fluently.",
        "paper_weight": 0.20,
        "command_words": ["Differentiate", "Calculate", "Show"],
    },
    {
        "id": "IB_PHYSICS_P2_FIELDS_IB_PHY_4_1",
        "objective_id": "IB_PHY_P2_4.1_A",
        "board": "IB",
        "subject": "Physics",
        "paper": "Paper 2",
        "topic": "Fields",
        "sub_topic": "Field Models",
        "code": "IB-PHY-4.1",
        "title": "Field models",
        "description": "Use field models and representations in structured exam responses.",
        "paper_weight": 0.21,
        "command_words": ["Explain", "Discuss", "Evaluate"],
    },
]
