/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=DocumentVisionBindings src/generated-bindings.d.ts` (hash: bac67fe556cd3db8257d54ec64a44784)
interface __BaseEnv_DocumentVisionBindings {
	AI: Ai;
	GEMINI_MODEL: "gemini-3.5-flash-lite";
	GEMINI_PRIVACY_MODE: "unverified";
	WORKERS_AI_PRIVACY_MODE: "unverified";
	AXON_VISION_VERSION: "1.0.0";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_DocumentVisionBindings {}
}
interface DocumentVisionBindings extends __BaseEnv_DocumentVisionBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "GEMINI_PRIVACY_MODE" | "WORKERS_AI_PRIVACY_MODE" | "AXON_VISION_VERSION">> {}
}
