/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=DocumentVisionBindings src/generated-bindings.d.ts` (hash: 9fd83b9745e3577353dd751c1f41025b)
interface __BaseEnv_DocumentVisionBindings {
	AI: Ai;
	GEMINI_PRIVACY_MODE: "unverified";
	WORKERS_AI_PRIVACY_MODE: "unverified";
	AXON_VISION_VERSION: "1.0.0";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_DocumentVisionBindings {}
}
interface DocumentVisionBindings extends __BaseEnv_DocumentVisionBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_PRIVACY_MODE" | "WORKERS_AI_PRIVACY_MODE" | "AXON_VISION_VERSION">> {}
}
