/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=IntelligenceBindings src/generated-bindings.d.ts` (hash: cf3ad2daa316a499cc24eb6139f51529)
interface __BaseEnv_IntelligenceBindings {
	PIPELINE_CACHE: KVNamespace;
	PAPER_ARTIFACTS: R2Bucket;
	DB: D1Database;
	PAPER_QUEUE: Queue;
	AXON_DEPLOYMENT_SHA: "development";
	AXON_CONFIG_REVISION: "v3.default";
	AXON_PIPELINE_VERSION: "3.0.0";
	GEMINI_PRIVACY_MODE: "unverified";
	TAVILY_API_BASE: "https://api.tavily.com";
	SUPABASE_URL: "https://dlgcqieyevoebefhcggi.supabase.co";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_IntelligenceBindings {}
}
interface IntelligenceBindings extends __BaseEnv_IntelligenceBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AXON_DEPLOYMENT_SHA" | "AXON_CONFIG_REVISION" | "AXON_PIPELINE_VERSION" | "GEMINI_PRIVACY_MODE" | "TAVILY_API_BASE" | "SUPABASE_URL">> {}
}
