/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=IntelligenceBindings src/generated-bindings.d.ts` (hash: 28d768f9af22904f42a463b0737a6c98)
interface __BaseEnv_IntelligenceBindings {
	PIPELINE_CACHE: KVNamespace;
	DB: D1Database;
	AXON_DEPLOYMENT_SHA: "development";
	AXON_CONFIG_REVISION: "v3.tutor" | "v3.default";
	AXON_PIPELINE_VERSION: "3.0.0";
	GEMINI_PRIVACY_MODE: "unverified";
	AXON_VISION_PRIVACY_MODE: "unverified";
	TAVILY_API_BASE: "https://api.tavily.com";
	SUPABASE_URL: "https://dlgcqieyevoebefhcggi.supabase.co";
	AXON_PROFILE: "tutor" | "full";
	PAPER_ARTIFACTS?: R2Bucket;
	PAPER_QUEUE?: Queue;
	DOCUMENT_VISION?: Fetcher /* axon-document-vision */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface TutorEnv {
		PIPELINE_CACHE: KVNamespace;
		DB: D1Database;
		AXON_DEPLOYMENT_SHA: "development";
		AXON_CONFIG_REVISION: "v3.tutor";
		AXON_PIPELINE_VERSION: "3.0.0";
		GEMINI_PRIVACY_MODE: "unverified";
		AXON_VISION_PRIVACY_MODE: "unverified";
		TAVILY_API_BASE: "https://api.tavily.com";
		SUPABASE_URL: "https://dlgcqieyevoebefhcggi.supabase.co";
		AXON_PROFILE: "tutor";
	}
	interface Env extends __BaseEnv_IntelligenceBindings {}
}
interface IntelligenceBindings extends __BaseEnv_IntelligenceBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AXON_DEPLOYMENT_SHA" | "AXON_CONFIG_REVISION" | "AXON_PIPELINE_VERSION" | "GEMINI_PRIVACY_MODE" | "AXON_VISION_PRIVACY_MODE" | "TAVILY_API_BASE" | "SUPABASE_URL" | "AXON_PROFILE">> {}
}
